# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=16
dpi-aware=yes
terminal=alacritty
layer=overlay
width=22
lines=10
icon-theme=Gruvbox-Plus-Dark

[colors]
background=1f1f28dd

text=dcd7baff
match=ffa066ff

selection=2d4f67ff
selection-text=dcd7baff
selection-match=ff5d62ff

border=957fb8ff

[border]
width=2
radius=6
