# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=14
dpi-aware=yes
terminal=alacritty
layer=overlay
width=25
lines=10
icon-theme=Gruvbox-Plus-Dark

[colors]
background=1a1b26dd

text=c0caf5ff
match=bb9af7ff

selection=292e42ff
selection-text=c0caf5ff
selection-match=bb9af7ff

border=7aa2f7ff

[border]
width=2
radius=6