# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=16
dpi-aware=yes
terminal=alacritty
layer=overlay
width=22
lines=10
icon-theme=Gruvbox-Plus-Dark

[colors]
background=282828dd

text=ebdbb2ff
match=fabd2fff

selection=3c3836ff
selection-text=ebdbb2ff
selection-match=d3869bff

border=d79921ff

[border]
width=2
radius=6
