# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font SemiBold:size=16
dpi-aware=yes
terminal=alacritty
layer=overlay
width=22
lines=10
icon-theme=Gruvbox-Plus-Dark

[colors]
background=181818dd

text=e4e4e4ff
match=95a99fff

selection=52494eff
selection-text=f5f5f5ff
selection-match=ffdd33ff

border=95a99fff

[border]
width=2
radius=6
