#regras de janela
[window]
opacity = 1
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"

#fonts
[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

#cores
[colors.primary]
background = "#181818"
foreground = "#E4E4E4"

[colors.normal]
black   = "#181818"
red     = "#F43841"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#9E95C7"
cyan    = "#95A99F"
white   = "#E4E4E4"

[colors.bright]
black   = "#52494E"
red     = "#FF4F58"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#AFAFD7"
cyan    = "#95A99F"
white   = "#F5F5F5"
